/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}', './node_modules/flowbite/**/*.js'],
  theme: {
    colors: {
      "secondary": "#226a58",
      "on-secondary": "#ffffff",
      "on-background": "#191c1d",
      "inverse-on-surface": "#eff1f1",
      "outline-variant": "#bfc9c4",
      "surface-dim": "#d8dada",
      "on-tertiary-fixed": "#370d0a",
      "primary-container": "#7db8a5",
      "on-primary-container": "#04493b",
      "on-error-container": "#93000a",
      "secondary-fixed": "#aaf1da",
      "secondary-fixed-dim": "#8fd4be",
      "secondary-container": "#aaf1da",
      "on-surface": "#191c1d",
      "on-primary-fixed-variant": "#105041",
      "surface-container-lowest": "#ffffff",
      "surface-variant": "#e1e3e3",
      "primary": "#2e6858",
      "on-tertiary": "#ffffff",
      "surface-bright": "#f8fafa",
      "on-surface-variant": "#404945",
      "inverse-primary": "#97d3bf",
      "tertiary": "#894e47",
      "surface-tint": "#2e6858",
      "on-secondary-fixed-variant": "#005141",
      "background": "#f8fafa",
      "primary-fixed": "#b2efda",
      "error": "#ba1a1a",
      "tertiary-container": "#e29a91",
      "outline": "#707975",
      "surface": "#f8fafa",
      "surface-container": "#eceeee",
      "on-tertiary-fixed-variant": "#6d3831",
      "on-secondary-container": "#29705e",
      "on-primary-fixed": "#002019",
      "on-secondary-fixed": "#002019",
      "tertiary-fixed-dim": "#ffb4aa",
      "on-primary": "#ffffff",
      "on-tertiary-container": "#65312b",
      "tertiary-fixed": "#ffdad5",
      "surface-container-low": "#f2f4f4",
      "surface-container-high": "#e6e8e9",
      "inverse-surface": "#2e3131",
      "error-container": "#ffdad6",
      "on-error": "#ffffff",
      "surface-container-highest": "#e1e3e3",
      "primary-fixed-dim": "#97d3bf"
    },
    extend: {
      fontFamily: {
        headline: ['Manrope', 'Plus Jakarta Sans', 'sans-serif'],
        body: ['Manrope', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [require('flowbite/plugin')],
};